export const std = [
    'help',

    'Core:v',
    'Core:ai',
    'Core:not',
    'Core:eq',
    'Core:neq',
    'Core:and',
    'Core:or',
    'Core:add',
    'Core:sub',
    'Core:mul',
    'Core:pow',
    'Core:div',
    'Core:mod',
    'Core:gt',
    'Core:lt',
    'Core:gteq',
    'Core:lteq',
    'Core:type',
    'Core:to_str',
    'Core:range',
    'Core:sleep',
    'Core:abort',

    'Util:uuid',

    'Json:stringify',
    'Json:parse',
    'Json:parsable',

    'Date:now',
    'Date:year',
    'Date:month',
    'Date:day',
    'Date:hour',
    'Date:minute',
    'Date:second',
    'Date:millisecond',
    'Date:parse',

    'Math:Infinity',
    'Math:E',
    'Math:LN2',
    'Math:LN10',
    'Math:LOG2E',
    'Math:LOG10E',
    'Math:PI',
    'Math:SQRT1_2',
    'Math:SQRT2',
    'Math:abs',
    'Math:acos',
    'Math:acosh',
    'Math:asin',
    'Math:asinh',
    'Math:atan',
    'Math:atanh',
    'Math:atan2',
    'Math:cbrt',
    'Math:ceil',
    'Math:clz32',
    'Math:cos',
    'Math:cosh',
    'Math:exp',
    'Math:expm1',
    'Math:floor',
    'Math:fround',
    'Math:hypot',
    'Math:imul',
    'Math:log',
    'Math:log1p',
    'Math:log10',
    'Math:log2',
    'Math:max',
    'Math:min',
    'Math:pow',
    'Math:round',
    'Math:sign',
    'Math:sin',
    'Math:sinh',
    'Math:sqrt',
    'Math:tan',
    'Math:tanh',
    'Math:trunc',
    'Math:rnd',
    'Math:gen_rng',

    'Num:to_hex',
    'Num:from_hex',

    'Str:lf',
    'Str:lt',
    'Str:gt',
    'Str:from_codepoint',
    'Str:from_unicode_codepoints',
    'Str:from_utf8_bytes',

    'Arr:create',

    'Obj:keys',
    'Obj:vals',
    'Obj:kvs',
    'Obj:get',
    'Obj:set',
    'Obj:has',
    'Obj:copy',
    'Obj:merge',

    'Error:create',

    'Async:interval',
    'Async:timeout',
];
